### ISSUE TITLE
Plugin fails to run if the Sketch file has never been saved

### ISSUE THREAD

**Issue by mageframe** [jawayang/Sketch-Base64-PNG-Export#2]
Line 30: var currentFilePath = [[doc fileURL] path];

Assumes that the Sketch file has been saved before. Recommend modifying script to throw in-app alert if value is not set and in the short term update README to highlight this constraint.

**Comment by jawayang** [comment]
I have remove the Line 30: var currentFilePath = [[doc fileURL] path];
because it is not use.
Thank you. @devinmancuso
