### ISSUE TITLE
Do not copy the code.

### ISSUE THREAD

**Issue by pavsmk** [jawayang/Sketch-Base64-PNG-Export#3]
See the video: https://youtu.be/0SyKtXnUPQA

Sketch 42 (36781)
macOS Sierra 10.12.3 (16D32)

**Comment by almarcotte** [comment]
Having the same issue, exact same specs. Both the CSS and HTML export don't seem to copy the code to the clipboard.

**Comment by stephenedmondson** [comment]
+1 Having the same issue

Sketch 42
macOS Sierra 10.12.3

**Comment by nicobrenner** [comment]
Same. Sketch 42 (36781) / OS X El Capitan 10.11.6

**Comment by scheibome** [comment]
Same. Sketch 43.2 (39069)

**Comment by g3wd** [comment]
what a great plugin idea. 
Unfortunately i got this issue too.
Sketch 43.2 (39069)
Mac OS 10.12.4 (16E195)

**Comment by jawayang** [comment]
Thanks, guys, I have fixed this bugs.
